cluster.name: "docker-cluster"
network.host: 0.0.0.0
# transport.host: 0.0.0.0

# xpack.security.enabled: true
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.verification_mode: certificate
# xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
# xpack.security.transport.ssl.truststore.path: elastic-certificates.p12

# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.key:  certs/elasticsearch/elasticsearch.key
# xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
# xpack.security.transport.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
